### ISSUE TITLE
[epic] Main Layout Design

### ISSUE THREAD

**Issue by AhmadHRai** [ByteRunners/weather_react#1]
### The final website should look something **close** to this ( a mix of both):

![original-3860cbdbfb333c4132d34353d29f3b12](https://github.com/user-attachments/assets/dd60e798-034b-4b75-9bf1-fc0ce039b83c)

![original-1ec4d417df15e7b063e5384cdbd061fe](https://github.com/user-attachments/assets/ce2aae09-7ff6-49ba-855e-fd531838ec87)

- [x] show current weather
- [x] show weather for whole week
- [ ] show weather in popular cities
- [ ] change icons based on the temperature and weather condition (sunny/rain)
